auto: true

title: liuyongkang's blog
url: http://liuyongkang.org
feed: /atom.xml
permalink: /:year/:month/:day/:title
markdown: rdiscount
pygments: true
paginate: 8

author:
        name: liuyongkang
        email: liuyongkanglinux@gmail.com
        weibo: http://www.weibo.com/mengsuihonglan
        github: http://github.com/liuyongkang

copyright:
    - Design by <a href="http://liuyongkang.org" rel="friend" title="liuyongkang" target="_blank">liuyongkang</a> &copy; Copyright 2013
